spring: 

   profiles: 

      active: 

        - dev 

--- 

server: 

  port: 8201 

 

spring: 

  profiles: dev 

  application: 

      name: microconfig-test-client



--- 

server: 

  port: 8102 

 

spring: 

  profiles: beta 

  application: 

        name: microconfig-test-client

 

